In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits import mplot3d
from math import*
            
#Matrice orgmenté
def Matrice_orgmente(A,B):
    n=len(B)
    C=np.array([[None]*1]*n)
    C[:n,0]=B[0:n]
    A=np.append(A,C,axis=1)	
    return(A)
 
#Recherche de la colonne pivot_total'

def Colonne_pivot(A,i):
    m=len(A)
    max=0
    indice=np.array([None]*2)
    for j in range(i,m):
        if(max<fabs(A[i,j])):
            max=fabs(A[i,j])
            indice=[i,j]
    for j in range(i,m):
        if(max<fabs(A[j,i])):
            max=fabs(A[j,i])
            indice=[j,i]
    for j in range(i,m):
         if(max<fabs(A[m-1,j])):
             max=fabs(A[m-1,j])
             indice=[m-1,j]
    for j in range(i,m):
        if(max<fabs(A[j,m-1])):
            max=fabs(A[j,m-1])
            indice=[j,m-1]
    return(indice)
    
#Choix du pivot total
def Choix_pivot_total(A,i):
    m=len(A)
    (a)=Colonne_pivot(A,i)
    x=A[:m,i].copy()
    A[:m,i]=A[:m,int(a[1])]
    A[:m,int(a[1])]=x
    return(A)
    
#Choix du pivot portielle
def Choix_pivot_partielle(A,i):
    m=len(A)
    for k in range(i+1,m) :
        if (fabs(A[k,i])>fabs(A[i,i])):
            x=A[k,:m+1].copy()
            A[k,:m+1]=A[i,:m+1]
            A[i,:m+1]=x 
    return(A)
 
#Choix du pivot simple
def Choix_pivot_simple(A,i):
    m=len(A)
    ordre=0
    pivot=fabs(A[i,i])
    for k in range(i+1,m) :
        if (A[k,i]!=0):
            x=A[ordre,:m+1].copy()
            A[ordre,:m+1]=A[i,:m+1]
            A[i,:m+1]=x
    return(A)
    
#fonction écholonnée
def Echelonnée(A):
    m=len(A)
    for i in range(0,m):
        for j in range(i+1,m):
            if(A[i,i]!=0):
                coef=A[j,i]/A[i,i]
                A[j,:]=A[j,:]-coef*A[i,:]         
    for i in range(0,m):
        if(A[i,i]!=0):
            A[i,:]=A[i,:]/A[i,i]              
    return(A)
    
#fonction solution
def Calcule_solution(A):
    m=len(A)
    sol=[None]*m
    sol[m-1]=A[m-1,m]
    for i in range(m-2,-1,-1):
        som=0
        for j in range(i+1,m):
            som=som+A[i,j]*sol[j]
            sol[i]=A[i,m]-som
            sol=np.array(sol)
    return(sol)

#Resolution par Gauss simple
def Gauss_simple(A,B):
    m=len(A)
    (Mo)=Matrice_orgmente(A,B)
    for i in range(0,m):
        (Mp)=Choix_pivot_simple(Mo,i)
        if(Mp[i,i+1]!=0):
             (Mp)=Echelonnée(Mp)
        else:
            sol_p="Le pivot est nul donc, le systeme n'admet pas de solution avec cette methode."
            break
    (sol_p)=Calcule_solution(Mp)
    return(sol_p)
    
#Resolution par Gauss partielle
def Gauss_partielle(A,B):
    m=len(A)
    (Mo)=Matrice_orgmente(A,B)
    #print(Mo)
    for i in range(0,m):
        (Mp)=Choix_pivot_partielle(Mo,i)
        (Mp)=Echelonnée(Mp)  
    (sol_p)=Calcule_solution(Mp)
    return(sol_p)
    
  #Resolution par Gsuss total
def Gauss_total(A,B):
    m=len(A)
    Q=np.array([None]*m)
    (Mo)=Matrice_orgmente(A,B)
    for i in range(0,m):
        (Mt)=Choix_pivot_total(Mo,i)
       # print(Mt)
        (Q[i])=Colonne_pivot(A,i)
        (Mt)=Echelonnée(Mt)
    #print(Q[1][2])
    for i in range(0,m):
        if(int(Q[i][0])!=int(Q[i][1])):
            x=Mt[:m,int(Q[i][1])].copy()
            Mt[:m,int(Q[i][1])]= Mt[:m,int(Q[i][0])]
            x= Mt[:m,int(Q[i][1])]
   # print("\n\n",Mt)
    (sol_p)=Calcule_solution(Mt)
    return(sol_p)

#calcule de |||A–1||| noté Norme1 
def Norme_matricielle(A):
    m=len(A)
    som1=0 # ce un vecteur
    som2=0  
    for j in range(0,m):
        som1=som1+A[:,j]**2
    for i in range(0,m):
        som2=som2+som1[i]
    Norme=float(sqrt(som2))
    
    return(Norme)
    
#calcule de la norme d'un vecteur
def Norme_vecteur(U,V):
    m=len(U)
    som=0  
    for i in range(0,m):
        som=som+(U[i]-V[i])**2
    Norme=float(sqrt(som))
    
    return(Norme)

#calcule du produit scalaire des vecteurs
def Produit_scalaire(U,V):
    m=len(U)
    som=0
    for i in range(0,m):
        som=som+U[i]*V[i]
    return(som)

#calcule du produit matrice vecteur
def P_Matrice_vecteur(A,V):
       m=len(A)
       U=np.array([0]*m,float)
       for i in range(0,m):
           j=0
           p=0
           while(i<m and p<m):
               U[i]=U[i]+(A[i,j]*V[p])
               j=j+1
               p=p+1    
            
       return(U)  
       
def Matrice_triangulaire(A):
    m=len(A)
    E=np.array([[0]*m]*m)     
    F=np.array([[0]*m]*m)
    D=np.array([[0]*m]*m)
    for i in range(0,m):
        E[i,0:i]=A[i,:i]
        D[i,i]=A[i,i]
        for j in range(m-1,i,-1):
            F[i,j]=A[i,j]
    return(D,E,F) 

#matrice a diagomale domimante
def Matrice_diago_domi(A):
    m=len(A)
    x=0 ; y=0
    d1="Non" ;d2="Non"; d3="oui"
    for i in range(0,m):
        s1=0; s2=0
        for j in range(0,m):
            if(i!=j):
                s1=s1+fabs(A[i,j])
                s2=s2+fabs(A[j,i])
        a=fabs(A[i,i])
        if(s1<a  and s2<a):
            x=x+1
        elif((s1<a or s1==a)and (s2<a or s2==a)):
            y=y+1
    if(x==m):
        d2="oui"  #stricte domimante
    elif(y==m):
        d1="oui"    # diago_domimante
    else:
      d3="Non" # A n'est pas a diagonale domimante9
      
    return(d1,d2, d3)
 
 # permutation des ligne de la matrice pour lui rendre à diagonale domimante
def Reherche_matrice_diago_domi(A):
    m=len(A)
    (d1,d2,d3)=Matrice_diago_domi(A)
    for i in range(1,m):
       j=0
       while(j<m and d2=="Non"):
           x=A[i,:m+1].copy()
           A[i,:m+1]=A[j,:m+1]
           A[j,:m+1]=x
           (d1,d2,d3)=Matrice_diago_domi(A)
           j=j+1
       if(d2=="oui"):
           break
    C=np.array([[None]*m]*m,float) 
    B=A[:m,m]
    for i in range(0,m):
        C[i]=A[i,:m]
    return(C,B)
 
#Resolution par la methode de jacobi
def Gacobi(A,B,X0,preci, nb_iter):
    m=len(A)
    n=1
    X=np.array([[None]*m]*n,float) 
    E=np.array([[None]*m]*n,float) 
    A=Matrice_orgmente(A,B)
    (A,B)=Reherche_matrice_diago_domi(A)
    (d1,d2,d3)=Matrice_diago_domi(A)
    if (d2=="oui"):
          (D,E,F)=Matrice_triangulaire(A)
          inverse=np.linalg.inv(D)
          X[0][0:m]=X0[0:m] 
          G=E+F
          Q=P_Matrice_vecteur(A,X[0])
          (N)=Norme_vecteur(B,Q)
          E[0]=B-Q
          i=0
          while(N>preci and i<nb_iter):
              P=P_Matrice_vecteur(G,X[i])
              H=B-P
              x=P_Matrice_vecteur(inverse,H)
              X=np.append(X, [x],axis=0)
              Q=P_Matrice_vecteur(A,X[i+1])
              E=np.append(E, [B-Q],axis=0)
              (N)=Norme_vecteur(B,Q)
              i=i+1
          sol=X[i]
          nombre_iteration=i
    else:
        sol="Cette matrice n'est pas à diaganale domimante stricte donc le systeme admet pas de solution par la methode de jocobi"
        nombre_iteration="il est alors impossible de conaitre le nombre iteration de Jacobi dans ce cas. merci"
    
    return(sol,nombre_iteration)

#Resolution par la methode de Gauss seidel
def Gauss_seidel(A,B,X0,preci, nb_iter):
    m=len(A); n=1
    X=np.array([[None]*m]*n,float) 
    E=np.array([[None]*m]*n,float) 
    (d1,d2,d3)=Matrice_diago_domi(A)
    if (d2=="oui"):
          (D,L,U)=Matrice_triangulaire(A)
          inverse=np.linalg.inv(L+D)
          X[0][0:m]=X0[0:m] 
          Q=P_Matrice_vecteur(A,X[0])
          (N)=Norme_vecteur(B,Q)
          E[0]=B-Q
          i=0
          while(N>preci and i<nb_iter):
              P=P_Matrice_vecteur(U,X[i])
              H=B-P
              x=P_Matrice_vecteur(inverse,H)
              X=np.append(X, [x],axis=0)
              Q=P_Matrice_vecteur(A,X[i+1])
              E=np.append(E, [B-Q],axis=0)
              (N)=Norme_vecteur(B,X[i+1])
              i=i+1
          sol=X[i]
          nombre_iteration=i
    else:
        sol="La matrice associeé au syteme n'est pas à diaganale domimante donc le systeme admet pas de solution par la methode de Gauss seidel"
        nombre_iteration="le nombres d'iteration est inconnu car la methode ne converge pas."
        
    return(sol,nombre_iteration)

#Resolution par la methode  du gradient
def Gradient(A,B,X0,p):
    m=len(A); n=1
    X=np.array([[None]*m]*n,float) #grad_D
    P=np.array([None]*n,float) #pas_desc
    D=np.array([[None]*m]*n,float)
    inverse=np.linalg.inv(A)
    (N1)=Norme_matricielle(inverse)
    X[0][0:m]=X0[0:m]  #condition fixé
    (Ad)=P_Matrice_vecteur(A,X[0])
    (N2)=Norme_vecteur(Ad,B)
    k=0
    while(N2<p*N1 or N2==p*N1 ):
        d=B-Ad   #direction
        D=np.append(D, [d],axis=0)#Enre_dir
        (dd)=Produit_scalaire(d,d)
        (Ad)=P_Matrice_vecteur(A,d)
        (P_Ad_d)=Produit_scalaire(Ad,d)
        y=dd/P_Ad_d #Enregistre_pas
        P=np.append(P, [y],axis=0)
        x=X[k][0:m]+P[k]*d[0:m]
        X=np.append(X, [x],axis=0)
        (Ad)=P_Matrice_vecteur(A,X[k+1])
        (N2)=Norme_vecteur(Ad,B)
        k=k+1
    ordre=k #position_solution dans X
    return(X[ordre-1])

#Resolution par la methode  du gradient conjugué
def Grandient_conjugue(A,B,X0,p):
    m=len(A);n=1
    Y=np.array([[None]*m]*n,float) 
    P1=np.array([None]*n,float) #Enre_pas
    D1=np.array([[None]*m]*n,float)
    inverse=np.linalg.inv(A)
    (N1)=Norme_matricielle(inverse)
    Y[0][0:m]=X0[0:m]
    (Ad)=P_Matrice_vecteur(A,Y[0])
    (N2)=Norme_vecteur(Ad,B)
    D1[0][0:m]=B-Ad
    j=0
    while(N2<p*N1 or N2==p*N1 ):
         R=B-Ad  
         q=0; som=0
         while(q<j):
            (Q)=P_Matrice_vecteur(A,D1[j])
            (a)=Produit_scalaire(Q,D1[q])
            (G)=P_Matrice_vecteur(A,D1[q])
            (b)=Produit_scalaire(G,D1[q])
            som=som+(a/b)*D1[q]
            q=q+1
         V=R-som
         D1=np.append(D1, [V],axis=0)
         (a1)=Produit_scalaire(D1[j],R)
         (Q1)=P_Matrice_vecteur(A,D1[j])
         (a2)=Produit_scalaire(Q1,D1[j])
         c=a1/a2
         P1=np.append(P1, [c],axis=0)
         y=Y[j][0:m]+P1[j]*D1[j][:m]
         Y=np.append(Y, [y],axis=0)
         (Q2)=P_Matrice_vecteur(A,Y[j+1])
         (N2)=Norme_vecteur(Q2,B)
         j=j+1
    ordre=j ##position_solution dans Y
    return(Y[ordre-1])

#Entrer votre syteme AX=B ici
#Quelques exemples
#A=np.array([[2,3,3,1],[-4,-6,3,2],[-1,1,1,1],[-2,1,1,1]])
#B=[15,3,5,1]
#A=np.array([[1,1],[2,-1]])
#B=[2,4]
A=np.array([[-4,1,0],[1,-4,1],[0,1,-4]])
B=[1,2,3]
#A=np.array([[-4,1,0],[1,-4,1],[0,1,-4]])
#A=np.array([[-2,2,1],[1,3,2],[1,-2,0]])
#B=[1,2,3]
#A=np.array([[9,4,1], [1,-2,-6], [1,6,0]])
#B=[17,14,4]

#condition iniatiale pour les methode iteratives
p=30
preci=0.00000001
nb_iter=18
#X0=[0,0,0,0]

#X0=[0,0,0]
X0=[5,2,1,0]


#lprint(z)
#print(x)
#print("\n\n",inverse)
#print("\n\n",A)
#print("\n\n",N1)
#print("\n\n",Ad)
#print(d)
#print("\n\n",X)
#print("\n\n",D)
#print("\n\n",P)
#print(ordre)
#print(X[ordre-1])
 
 
#solution du syteme Ax=B
print("\nLa solution du syteme AX=B avec\n\nA=",A ,"et B=",B ,"est le vecteur:\n\n1.1)  Solution par la methode de Gauss simple\n\n X=",Gauss_simple(A,B),"\n\n1.2) Solution par la methode de Gauss total:\n\n X=",Gauss_total(A,B),"\n\n 1.3) Solution par la methode de Gauss partielle:\n\n X=",Gauss_partielle(A,B),"\n\n 1.4) Solution par la methode de Jacobi:\n\n",Gacobi(A,B,X0,preci, nb_iter),"\n\n 1.5) Solution par la methode de Gauss seidel :\n\n",Gauss_seidel(A,B,X0,preci, nb_iter),"\n\n 1.6)  Solution par la methode du gradient est:\n\n X=",Gradient(A,B,X0,p),"\n\n 1.7)  Solution par la methode du gradient conjugué est:\n\n X=",Grandient_conjugue(A,B,X0,p))



#soltution avec un fonction python

b=np.array(B)
x=np.linalg.solve(A,b)
print("\n 1,8)  La solution avec un fonction  python est:\n\n X=",x)



La solution du syteme AX=B avec

A= [[-4  1  0]
 [ 1 -4  1]
 [ 0  1 -4]] et B= [1, 2, 3] est le vecteur:

1.1)  Solution par la methode de Gauss simple

 X= [-0.4642857142857143 -0.8571428571428571 -0.9642857142857143] 

1.2) Solution par la methode de Gauss total:

 X= [-0.4642857142857143 -0.8571428571428571 -0.9642857142857143] 

 1.3) Solution par la methode de Gauss partielle:

 X= [-0.4642857142857143 -0.8571428571428571 -0.9642857142857143] 

 1.4) Solution par la methode de Jacobi:

 (array([-0.46428569, -0.85714284, -0.96428569]), 18) 

 1.5) Solution par la methode de Gauss seidel :

 (array([-0.46428571, -0.85714286, -0.96428571]), 18) 

 1.6)  Solution par la methode du gradient est:

 X= [5. 2. 1.] 

 1.7)  Solution par la methode du gradient conjugué est:

 X= [5. 2. 1.]

 1,8)  La solution avec un fonction  python est:

 X= [-0.46428571 -0.85714286 -0.96428571]
